### ISSUE TITLE
Logs feature currently not working over midnight

### ISSUE THREAD

**Issue by Eremiell** [United-Programming/UPBot#96]
The way bot currently logs things is it creates a new log file per server per run, using the current date as part of the filename. This is perfectly fine from backend point of view and also makes perfect sense for availability of logs around midnight.

Issue is the bot always looks for file with current date in the name it seems, which may not exist, s the bot may be running over the date threshold.

Seeing two possible solutions here:

1) Make bot aware of the last time it started. This info may be useful in other means as well (e.g. we can flex it in stats), and then look for file with that date in it. This would provide continuity of the long for the whole duration of the bot uptime.

2) Make bot create a new logfile every UTC midnight.

**Comment by CPULL** [comment]
Probably I will keep a list of strings in the Utils to keep track of the last log file per guild.

**Comment by CPULL** [comment]
Fixed here: 
[commit d48262f10a6c75ef95a88ce89778ac3f3857223d](https://github.com/United-Programming/UPBot/commit/d48262f10a6c75ef95a88ce89778ac3f3857223d)
