### ISSUE TITLE
C++ code identifies as C#

### ISSUE THREAD

**Issue by Eremiell** [United-Programming/UPBot#99]
This particular piece of code got identified as C# while clearly being C++.

```cpp
int main() {
  /* Enter your code here. Read input from STDIN. Print output to STDOUT */
  string s;
  getline(cin, s);
  int sum =0;
  for (size_t i = 0; i < s.length(); i++) {
    /* code */
  }
  cout << sum << endl;
  return 0;
}
```

Some common eye catches here would be `getline` (which can be also C), `cin`, `cout`, and `endl`, probably also `size_t` (which can be also C).

While this code clearly represents rather a beginner's attempt at C++ than a modern desired piece of code, that is after all what we deal with most of the time in the server (esp. when it mes to the reformat utility).

As discussed, I'll try to provide some list of common tokens to look for later.

**Comment by UnitedProgrammingDiscord** [comment]
Fixed in version 0.3.0
